In [1]:
import numpy as np

In [22]:
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])

c = np.arange(2,30)

In [23]:
a+b # per fare operazioni di questo tipo gli array devono essere lunghi uguali

array([3, 4, 5, 6])

In [24]:
a**2

array([ 1,  4,  9, 16])

In [25]:
a%2

array([1, 0, 1, 0])

In [26]:
a**2+b/3

array([ 1.66666667,  4.66666667,  9.66666667, 16.66666667])

In [27]:
a%2==0

array([False,  True, False,  True])

In [28]:
np.concatenate((a,b))

array([1, 2, 3, 4, 2, 2, 2, 2])

In [29]:
def is_prime(n):
    for i in range(2,int(np.sqrt(n)+1)):
        if n%2 == 0: return False
    return True

In [30]:
is_prime(11)

True

In [32]:
is_prime_v = np.vectorize(is_prime) # trasformazione in una funzione universale anche detta vettorizzata

In [41]:
is_prime_v(c)

array([ True,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
# per ottenere la lista dei numeri primi faccio:

c[is_prime_v(c)]

array([ 2,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [37]:
# per fare una matrice di 8 posso fare:
np.ones(shape=(10,10))*8

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [39]:
np.pi # pi greco

3.141592653589793

In [ ]:
np.nonzero() # restituisce l'indice degli elementi che non sono a zero o a False
np.count_nonzero() # restituisce quanti valori non sono a zero o a False

In [42]:
np.nonzero(c)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]),)