In [2]:
import numpy as np

### Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0)

In [3]:
# si nota che la somma degli indici (x+y)%2 da come risultato un alternaza di 0 e 1 come desiderato

indici_uno = np.array([[i,j] for i in range(8) for j in range(8) if (i+j)%2==1])
indici_uno # è un array di indici dove bisogna inserire 1 nella matrice

array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7],
       [1, 0],
       [1, 2],
       [1, 4],
       [1, 6],
       [2, 1],
       [2, 3],
       [2, 5],
       [2, 7],
       [3, 0],
       [3, 2],
       [3, 4],
       [3, 6],
       [4, 1],
       [4, 3],
       [4, 5],
       [4, 7],
       [5, 0],
       [5, 2],
       [5, 4],
       [5, 6],
       [6, 1],
       [6, 3],
       [6, 5],
       [6, 7],
       [7, 0],
       [7, 2],
       [7, 4],
       [7, 6]])

In [4]:
Z = np.zeros(shape=(8,8))
Z[indici_uno.T[0],indici_uno.T[1]]=1 
# con .T indico di transporre, ovvero scambio le righe con le colonne
# indici_uno.T[0] --> si riferisce alle x
# indici_uno.T[1] --> si riferisce alle y
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
#MODO 2
#mat[::2, significa prendi tutto di due in due]
mat_2 = np.ones((8,8), dtype=int)
mat_2[::2,::2] = 0
mat_2[1::2,1::2] = 0
mat_2

### Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [11]:
Z = np.arange(1,15) # genero array
Z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

0,1,2,3,1,2,3,4,2,3,4,5

In [15]:
indici= np.array([i+j for i in range(0,11) for j in range(0,4)])
indici

array([ 0,  1,  2,  3,  1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,
        5,  6,  7,  5,  6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10,  8,  9,
       10, 11,  9, 10, 11, 12, 10, 11, 12, 13])

In [17]:
Z[indici].reshape((11,-1)) 
# con il reshape io modifico la forma dell'oggetto, con -1 indico che si deve calcolare lui l'altra dimensione

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

### Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [30]:
s = 10
Z = np.zeros(shape=(s,s))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
for i in range(s-1,-1,-1): 
    # io con il primo -1 indico di arrivare nel conteggio fino a 0, 
    # mentre con il secondo -1 indico di andare di -1 in -1 (si conta al contrario, decrescente)
    Z[:,i] = i+1
    Z[:,s-i-1] = i+1
    Z[i,:] = i+1
    Z[s-i-1,:] = i+1
    
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 5., 5., 4., 3., 2., 1.],
       [1., 2., 3., 4., 4., 4., 4., 3., 2., 1.],
       [1., 2., 3., 3., 3., 3., 3., 3., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile. 

### Piccola parentesi di statistica
Vediamo alcuni concetti che ci possono servire:
* La *media dei valori*, che in numpy si calcola così: `np.average(nome_array)`
* La *deviazione standard* che è un parametro che che misura quanto i valori sono concentrati attorno alla media. 
    Sarebbe il 68% dell'area sotto la Gaussiana e si calcola facendo *la radice quadrata della differenza tra la
    media dei quadrati e la media al quadrato*:
    
    ` m_2 = 1/n(x_1²+x_2²+...+x_n²) `
    
    `dev_std = sqrt(m_2-m²)`
* La *varianza* che è il quadrato della deviazione standard:
    ``v=(m_2-m²)``

In [35]:
altezze = np.array([171,184,167,162,173,174,178,159])
altezze

array([171, 184, 167, 162, 173, 174, 178, 159])

In [36]:
media = np.average(altezze)
media

171.0

In [44]:
altezze_quadrato = altezze**2
altezze_quadrato

array([29241, 33856, 27889, 26244, 29929, 30276, 31684, 25281])

In [45]:
media_quadrato = np.average(altezze_quadrato)
media_quadrato

29300.0

In [46]:
devstd = np.sqrt(media_quadrato-media**2)
devstd

7.681145747868608

In [47]:
np.random.normal(media,devstd,15)

array([184.15901427, 183.71780327, 175.02213192, 170.69129102,
       163.40261051, 179.21660225, 166.18119807, 179.03073133,
       161.48822036, 169.39015682, 177.02456579, 171.61506681,
       178.21560004, 172.30743195, 170.83980436])