In [27]:
import numpy as np

### ES 1
Creare una funzione che inverta un ndarray monodimensionale, ovvero crei un array monodimensionale con gli stessi elementi dell'array di partenza in ordine inverso.

#### CREAZIONE FUNZIONE PER INVERTIRE ARRAY

In [28]:
def inverti(lista):
    """
    new_lista = []
    for i in range(1, len(lista)+1):
        new_lista.append(lista[-i]) # con -i ciclo partendo dall'ultimo elemento
    return new_lista
    """
    
    # OPPURE
    
    return [lista[-i] for i in range(1, len(lista)+1)]

#### CREAZIONE ARRAY MONODIMENSIONALE

In [29]:
array = np.array([1,4,6,8,9,0])
array

array([1, 4, 6, 8, 9, 0])

In [30]:
array_invertito = inverti(array)
array_invertito

[0, 9, 8, 6, 4, 1]

### ES 2
Generare un array Numpy che contenga le posizioni dei primi 100 numeri primi all'interno dei numeri naturali. 

#### CREAZIONE COSTANTI

In [31]:
NUM_NUMERI_PRIMI = 100

#### CREAZIONE FUNZIONE PER GENERARE NUMERI REALI PRIMI

In [32]:
def generatore_n_numeri_reali_primi():
    num = 2;
    num_primi = []
    while(len(num_primi) < NUM_NUMERI_PRIMI):
        
        cond = True
        for i in range(2, int(num/2)+1):
            if num%i == 0: cond = False # per ottimizzarlo bisognerebbe fare un ciclo while e farlo uscire appena cond = False
        
        if cond: num_primi.append(num)
        
        num+=1
    
    return np.array(num_primi) 

In [33]:
generatore_n_numeri_reali_primi()

array([  2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,  41,
        43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97, 101,
       103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167,
       173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239,
       241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313,
       317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397,
       401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
       479, 487, 491, 499, 503, 509, 521, 523, 541])

### ES 3
Generare un array Numpy contenente i primi 10 numeri di Fibonacci 

#### CREAZIONE COSTANTI

In [34]:
NUM_FIBONACCI = 10

#### CREAZIONE FUNZIONE PER GENERARE NUMERI REALI PRIMI

In [35]:
def generatore_n_numeri_fibonacci():
    num_fib = [1,1]
    for i in range(2, NUM_FIBONACCI):
        num_fib.append(num_fib[i-1]+num_fib[i-2])
        
    return np.array(num_fib)

In [36]:
generatore_n_numeri_fibonacci()

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55])