In [2]:
import numpy as np

## Broadcast

In [3]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a +5

# questa cosa qui si chiama broadcast ovvero che la somma viene diffusa su tutti gli elementi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
b = a.reshape((-1,3))
b

# se mettessi al posto di 4 -1 numpy calcolerebbe lui la sua dimensione

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
c = np.ones(3)*100
c

array([100., 100., 100.])

In [15]:
# se faccio b + c
b + c

# in questo caso è appena avvenuto il broadcast riga per riga

array([[100., 101., 102.],
       [103., 104., 105.],
       [106., 107., 108.],
       [109., 110., 111.]])

In [18]:
# se io avessi sommato a b una array più lungo o più corto, avrebbe dato errore, dato che non sarebbero corrisposte
# le lunghezze delle righe

c = np.ones(4)*100
b + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

### ESEMPIO

In [ ]:
import uuid

In [25]:
n_passeggeri = 2000000
temperature = np.random.normal(36.5, 0.25, n_passaggeri)
identificativi = np.array([str(uuid.uuid4()) for _ in range(n_passeggeri)])

In [26]:
%%timeit # permette di capire quato tempo impiega ad eseguire il codice dentro una cella

contatore = np.count_nonzero(temperature > 37.5)

56.8 µs ± 349 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
