In [37]:
import numpy as np

### CONVERTIRE UNA LISTA IN ARRAY NUMPY

In [38]:
lista  = [1,2,3,4,5,6]
lista_array = np.array(lista)
print(lista_array)

[1 2 3 4 5 6]


### CREAZIONE ARRAY DI INTERI CONTENENTI 0

In [39]:
np.zeros(10, dtype=np.int)  # il dype può anche essere int (tipo di python)

<ipython-input-39-27809ce09c4d>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(10, dtype=np.int)  # il dype può anche essere int (tipo di python)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### CREAZIONE MATRICE DI INTERI CONTENENTI 0

In [40]:
np.zeros((5,10), dtype=np.int)

<ipython-input-40-a9efce7bcf5e>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((5,10), dtype=np.int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### NUMERI CASUALI

Apprfondimento:
i ""numeri pseudocasuali"" sono numeri che sembrano casuali ma sono generati da un algoritmo deterministico,
infatti nella funzione che genera questi numeri si passa anche un seme (ovvero un valore di partenza).

Una probabilità si dice uniforme se ogni caso ha la stessa probabilità di uscire (tipo un dado).

Per estrarre un numero uniforme si fa:

In [41]:
np.random.uniform()

0.41430104801600987

In [42]:
np.random.uniform(size=100) # con size gli dico di creare un lista di numeri uniformi lunga n

array([0.50351068, 0.44101916, 0.93089299, 0.31168753, 0.03719034,
       0.12307206, 0.77382942, 0.85968793, 0.93228854, 0.21003721,
       0.24838483, 0.12952423, 0.46200453, 0.62402597, 0.35859236,
       0.91128213, 0.3291085 , 0.35558321, 0.94990525, 0.34119589,
       0.74516054, 0.90463689, 0.77738632, 0.14825222, 0.39931785,
       0.63413389, 0.5208676 , 0.06808148, 0.11403935, 0.78790769,
       0.95061348, 0.07973281, 0.96453921, 0.70431089, 0.89988528,
       0.71162755, 0.42124139, 0.62166735, 0.5045858 , 0.72584955,
       0.61916298, 0.7262708 , 0.43771148, 0.11463047, 0.15171398,
       0.66287993, 0.00989454, 0.52928205, 0.61713329, 0.56458303,
       0.13798055, 0.39956301, 0.92815987, 0.74593939, 0.62964055,
       0.33021601, 0.31387743, 0.84546544, 0.61912266, 0.4696066 ,
       0.05475632, 0.32901503, 0.66630669, 0.50710609, 0.83387179,
       0.61061604, 0.91180982, 0.76284068, 0.96219115, 0.32657741,
       0.76953995, 0.72603797, 0.97393123, 0.05048845, 0.01288

Una distribuzione molto usata è quella GAUSSIANA (anche detta a campana o normale).

Con il parametro loc indico: il valore centrale (punto di massimo della funzione gaussiana)
Con il parametro scale indico: quanto è larga la funzione gaussiana

In [43]:
np.random.normal(loc=10, scale=1, size=10)

array([ 8.79551837, 11.37374828, 10.37007577, 11.38772372, 10.16530717,
       11.5085432 ,  9.86461643,  8.51451032,  9.58731776, 10.4565111 ])

In [44]:
# RANDOM_INTEGERS --> SERVE PER ESTRARE DEI NUMERI INTERI CASUALI [low,high)

np.random.random_integers(low=1, high=7, size=10) 
# è la simulazione di 10 lanci di un dato
# si può anche usare np.random.randint()

<ipython-input-44-f96cbd8631eb>:3: DeprecationWarning: This function is deprecated. Please call randint(1, 7 + 1) instead
  np.random.random_integers(low=1, high=7, size=10)


array([1, 6, 3, 4, 5, 2, 3, 1, 1, 6])

In [45]:
np.random.choice(["testa", "croce"], size=10)

array(['testa', 'croce', 'croce', 'testa', 'testa', 'testa', 'croce',
       'croce', 'testa', 'croce'], dtype='<U5')

Dimensioni spaziali che servono per rappresentare gli array si utilizzano degli assi standard:
- l'array 1D si chiama asse0 (axis0)
- l'array 2D ha l'asse 0 quello delle righe e l'asse 1 quello delle colonne
- l'array 3D è uguale al 2D con l'asse 2 che è la profondità.

In [46]:
matrice = np.random.uniform(size=(4,5))
matrice

array([[0.39092684, 0.4374071 , 0.38091043, 0.52821836, 0.17929586],
       [0.83672189, 0.17376379, 0.56544659, 0.51575429, 0.06279393],
       [0.2199303 , 0.70035978, 0.73648422, 0.92254979, 0.86493638],
       [0.02234078, 0.27515489, 0.37678225, 0.1974602 , 0.16107683]])

In [47]:
# SHAPE --> SERVE PER RITORNARE IL NUMERO DI RIGHE E COLONNE DI UN OGGETTO NUMPY (1D,2D,ecc...)

np.shape(matrice)

(4, 5)

In [48]:
vettore = np.random.uniform(size=10)
vettore

array([0.9566392 , 0.86473183, 0.55640593, 0.93001845, 0.19408806,
       0.72891134, 0.93433326, 0.1528832 , 0.34665837, 0.68018083])

In [49]:
np.shape(vettore)

(10,)

### FUNZIONI UTILI

In [50]:
# RAVEL --> PERMETTE DI TRASFORMARE MATRICI IN ARRAY, ACCODANDO RIGA PER RIGA

matrice1 = np.ravel(matrice)
matrice1

array([0.39092684, 0.4374071 , 0.38091043, 0.52821836, 0.17929586,
       0.83672189, 0.17376379, 0.56544659, 0.51575429, 0.06279393,
       0.2199303 , 0.70035978, 0.73648422, 0.92254979, 0.86493638,
       0.02234078, 0.27515489, 0.37678225, 0.1974602 , 0.16107683])

In [51]:
# per accedere a degli elementi di un oggetto numpy (1D,2D,ecc...) si usano le quadre

matrice[0][1]

0.43740710118906867

In [52]:
# DA NOTARE:
# se io modifico un elemento in matrice1 verrà modificato anche in matrice (vuol dire che puntano alla stessa
# area di memoria, facendo così non si creano copie)

matrice1[0] = 12
print(f"matrice1: {matrice1}")
print(f"matrice: {matrice}")

matrice1: [12.          0.4374071   0.38091043  0.52821836  0.17929586  0.83672189
  0.17376379  0.56544659  0.51575429  0.06279393  0.2199303   0.70035978
  0.73648422  0.92254979  0.86493638  0.02234078  0.27515489  0.37678225
  0.1974602   0.16107683]
matrice: [[12.          0.4374071   0.38091043  0.52821836  0.17929586]
 [ 0.83672189  0.17376379  0.56544659  0.51575429  0.06279393]
 [ 0.2199303   0.70035978  0.73648422  0.92254979  0.86493638]
 [ 0.02234078  0.27515489  0.37678225  0.1974602   0.16107683]]


In [53]:
# RESHAPE --> SERVE A MODIFICARE LA FORMA DEGLI OGGETTI NUMPY
# si possono ridimensionare oggetti numpy solo con numeri di r e c che moltiplicati tra di loro danno un numero 
# uguale al prodotto di r e c iniziali

matrice.reshape((2,10))

array([[12.        ,  0.4374071 ,  0.38091043,  0.52821836,  0.17929586,
         0.83672189,  0.17376379,  0.56544659,  0.51575429,  0.06279393],
       [ 0.2199303 ,  0.70035978,  0.73648422,  0.92254979,  0.86493638,
         0.02234078,  0.27515489,  0.37678225,  0.1974602 ,  0.16107683]])

In [54]:
# TRANSPOSE --> SERVE A FARE UNA MATRICE TRASPOSTA (ovvero si invertono le righe con le colonne)

print(np.shape(matrice))
print(matrice.transpose())
print(np.shape(matrice))

(4, 5)
[[12.          0.83672189  0.2199303   0.02234078]
 [ 0.4374071   0.17376379  0.70035978  0.27515489]
 [ 0.38091043  0.56544659  0.73648422  0.37678225]
 [ 0.52821836  0.51575429  0.92254979  0.1974602 ]
 [ 0.17929586  0.06279393  0.86493638  0.16107683]]
(4, 5)


### ESEMPI

In [55]:
# ES 1:
# simulazione di lanci di un dato

lancio_dato = np.random.randint(low=1, high=7, size=10000)
lancio_dato

array([1, 2, 5, ..., 6, 2, 1])

In [56]:
# per verificare la presenza di un elemento dentro un oggetto numpy si può fare:
lancio_dato == 6

array([False, False, False, ...,  True, False, False])

In [57]:
# contiamo quanti 6 sono usciti ed in seguito dividiamo per 10000 per calcolarne la probabilità
np.count_nonzero(lancio_dato == 6)/10000

# al tendere di infiniti lanci la probabilità reale si avvicina alla probabilità statistica

0.1635

In [58]:
# per calcolare quante volte su 10000 lanci esce un numero >= 4 si fa:
np.count_nonzero(lancio_dato >=4)/10000

0.4949

In [59]:
# per calcolare quanti 4 sono usciti sui 10000 lanci di 2 dati si fa:

lancio_dato2 = np.random.randint(low=1, high=7, size=10000)
np.count_nonzero(lancio_dato + lancio_dato2 ==8)/10000

# facendo lancio_dato + lancio_dato2 io vado a sommare ogni singolo elemento dell'array lancio_dato con ogni singolo
# elemento dell'array lancio_dato2

# quindi se devo vedere la probabilità di quanti 4 sono usciti devo mettere 8 perche numpy somma le celle (4+4=8)

0.1319