In [9]:
import numpy as np

### 1) Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0) 

In [40]:
linea_scacchiera = np.array([x%2 for x in range(8)])
scacchiera = np.zeros((8,8), int)

for i in range(8):
    scacchiera[i] = linea_scacchiera
    linea_scacchiera = np.flipud(linea_scacchiera)
    
scacchiera

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 2) Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [90]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = np.array([])

for i in range(len(Z)-3):
        R = np.append(R, Z[[i,i+1,i+2,i+3]])       

R = np.resize(R, (11,4))   
R = R.astype(int)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

### 3) Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [72]:
lista_altezze = np.random.normal(170,10, 15)
lista_altezze = lista_altezze.astype(int)
lista_altezze

array([146, 151, 164, 179, 166, 173, 161, 167, 180, 162, 190, 163, 175,
       178, 177])

### 4) Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [107]:
dim_matrice = 10
num = int(dim_matrice/2)
matrice = np.zeros((dim_matrice,dim_matrice), int)

for i in range(int(dim_matrice/2), dim_matrice):
    
    matrice[dim_matrice-i-1,:][...] = num
    matrice[i,:][...] = num

    
    matrice[:,dim_matrice-i-1][...] = num
    matrice[:,i][...] = num
    
    
    num -= 1
    
matrice

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])