In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,12,45])
a

array([ 1,  2,  3, 12, 45])

In [4]:
for i, el in enumerate(a):
    print(el)
    print(a[i])

1
1
2
2
3
3
12
12
45
45


In [6]:
a[...]=5  # con i 3 puntini io indico di assegnare tutti i valori a 5
a

array([5, 5, 5, 5, 5])

In [8]:
b = a [1:4]
b[...] = 99
b

array([99, 99, 99])

In [9]:
a

array([ 5, 99, 99, 99,  5])

In [10]:
# noto che b comunque punta ad a, b è una view di a

In [11]:
# per capire se un array è la view di un altro array si fa:
b.base is a

True

In [13]:
# con le lieste di python è l'esatto contrario:
# - per fare copia di array numpy: a = b
# - per fare copia di array python: a = b[:]

# - per creare un array numpy che punta ad un altro array numpy: a = b[:]
# - per creare un array python che punta ad un altro array python: a = b

### Indicizzazione Fancing

In [14]:
f = [True,False,True,True,False]
a [f]

array([ 5, 99, 99])

In [16]:
h = a[f] # con l'indicizzazione fancing io creo delle copie
h

array([ 5, 99, 99])

In [18]:
h[...] = 66
h

array([66, 66, 66])

In [20]:
a  # io noto che il mio array iniziale non si è modificato

array([ 5, 99, 99, 99,  5])

### esempio

In [23]:
dato_Alice = np.random.randint(1,7,10)
dato_Bob = np.random.randint(1,7,10)

print(dato_Alice)
print(dato_Bob)

[6 4 4 3 4 3 6 1 6 2]
[6 5 1 2 3 5 1 4 5 2]


In [24]:
dato_Alice > dato_Bob # per vedere quante volte Alice ha vinto

array([False, False,  True,  True,  True, False,  True, False,  True,
       False])

In [27]:
# e per vedere con che lanci ha vinto Alice faccio:
lanci_vittoria_Alice = dato_Alice[dato_Alice>dato_Bob]
lanci_vittoria_Alice

array([4, 3, 4, 6, 6])

In [30]:
lanci_vittoria_Alice.base is dato_Alice

False

### Altro modo di fare indicizzazione fancing

In [38]:
# apposto di passargli una lista di boolean, gli passo una lista degli indici che voglio
l = a[[4,0,3]]
l

array([ 5,  5, 99])

In [36]:
l.base in a

False

In [39]:
# tutto ciò è valido anche con le matrici

In [41]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
mat[0] # ottengo la prima riga

array([1, 2, 3])

In [43]:
mat[0][0] # ottengo il primo elemento

1

In [47]:
mat[0,0] # indicizzazione tipo matematica x e y

1

In [49]:
prima_colonna = mat[:,0] # io con i due punti indico prendi tutte le righe e poi estrai quelle con indice 0
prima_colonna

array([1, 4, 7])

In [51]:
prima_colonna[...] = 11
prima_colonna

array([11, 11, 11])

In [53]:
mat # vedo che ho modificato anche mat

array([[11,  2,  3],
       [11,  5,  6],
       [11,  8,  9]])

In [54]:
prima_colonna.base in mat

True

In [59]:
mat1 = np.random.randint(0,2,size=(10,10))
mat1

array([[1, 1, 1, 0, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [64]:
mat1[:,0][...] = 0
mat1[:,9][...] = 0

mat1[0, :][...] = 0
mat1[9, :][...] = 0

mat1 # così metto sul bordo della matrice tutti zeri

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [71]:
mat2 = np.random.randint(0,2,size=(10,10))

print(mat2)
                         
mat2[:,0] = np.random.randint(1,10,10)
mat2[:,9] = np.random.randint(1,10,10)

mat2[0, :] = np.random.randint(1,10,10)
mat2[9, :] = np.random.randint(1,10,10)
                         
mat2

[[0 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 1 1 0 1]
 [0 1 1 1 1 1 1 0 0 1]
 [0 0 1 1 1 1 1 1 1 0]
 [1 1 0 1 0 0 1 0 0 1]
 [1 1 0 0 0 0 0 1 0 1]
 [0 1 1 0 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 0 0 1]
 [0 1 0 1 0 0 0 0 1 1]
 [0 0 1 0 1 1 1 0 0 1]]


array([[1, 5, 9, 7, 6, 6, 6, 7, 7, 4],
       [9, 0, 1, 1, 1, 1, 1, 1, 0, 8],
       [2, 1, 1, 1, 1, 1, 1, 0, 0, 8],
       [3, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 1, 0, 1, 0, 0, 1, 0, 0, 8],
       [5, 1, 0, 0, 0, 0, 0, 1, 0, 9],
       [2, 1, 1, 0, 1, 0, 0, 0, 0, 9],
       [7, 0, 1, 0, 0, 1, 0, 0, 0, 5],
       [7, 1, 0, 1, 0, 0, 0, 0, 1, 7],
       [2, 5, 1, 5, 5, 3, 6, 7, 2, 3]])