In [2]:
import numpy as np

## ESERCIZIO 1

Robot impazzito

Un braccio robotico industriale libero di muoversi avanti e indietro
lungo una rotaia è impazzito. Ogni secondo si muove scegliendo a caso
tra due possibili movimenti: 1 cm in avanti, oppure 1 cm indietro. Non è
possibile togliere corrente al robot senza bloccare tutto lo
stabilimento, quindi bisogna attendere lo spegnimento che si effettua
tutti i finesettimana e oggi purtroppo è lunedì! Il nostro responsabile
ci chiede di simulare lo spostamento totale che il robot avrà effettuato
dopo 5 interi giorni di pazzia. Il robot è partito dalla posizione
centrale della rotaia avente coordinata 0cm.

In [3]:
num_secondi_per_5_giorni = 5*24*60*60
lista = [1,-1]

In [4]:
generazione_movimenti = np.random.choice(lista, num_secondi_per_5_giorni)

spostamento = np.sum(generazione_movimenti)
spostamento

562

In [5]:
import random

spostamento = 0
for _ in range(num_secondi_per_5_giorni):
    spostamento += random.choice(lista)
    
spostamento

-136

## ESERCIZIO 2

Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno.

Per quanto riguarda l'esercizio dei compleanni, se volessimo calcolare *matematicamente* la probabilità che tutti abbiano il compleanno in un giorno diverso dovremmo fare:
`P_comp_differente = 365/365 * 364/365 * ... n volte` → quindi se definiamo `n` come il numero di persone in una classe, la formula è : `P_comp_differente = 364/365 * 365/365 * (365-n+1)/365`

Di conseguenza volessimo sapere la probabilità che in una classe ci siano 2 o più persone nate nello stesso giorno è:
`P_comp_uguale = 1 - P_comp_differente`

In [4]:
numero_classi = 1000
numero_alunni = 25

In [5]:
num_classi_con_studenti_nati_allo_stesso_giorno = 0

for _ in range(numero_classi):
    date_alunni = np.random.randint(1,365, numero_alunni)
    unique, counts = np.unique(date_alunni, return_counts=True)
    if np.count_nonzero(counts > 2) > 0:
        num_classi_con_studenti_nati_allo_stesso_giorno += 1
        
num_classi_con_studenti_nati_allo_stesso_giorno

26

In [6]:
import random

num_classi_con_studenti_nati_allo_stesso_giorno = 0

for _ in range(numero_classi):
    
    date_alunni = []
    for _ in range(numero_alunni):
        date_alunni.append(random.randint(0,365))
        
    a_set = set(date_alunni)
    contains_duplicates = len(date_alunni) != len(a_set)

    if contains_duplicates:
        num_classi_con_studenti_nati_allo_stesso_giorno += 1
        
num_classi_con_studenti_nati_allo_stesso_giorno

555

## ESERCIZIO 3

Dato un array monodimensionale di numeri, trovare la posizione di tutti i massimi locali. Ad esempio, dato l'array a = [0, 2, 1, 1, 3, 2], 2 e 3 sono massimi locali rispettivamente nelle posizioni 1 e 4.

In [5]:
array = [1,4,5,2,6,7,3,45,8,9]

In [11]:
from scipy.signal import argrelextrema

np_array = np.array(array)
indici_massimi_locali = argrelextrema(np_array, np.greater)

print(indici_massimi_locali)
print(np_array[indici_massimi_locali])


"""
Si potrebbero anche sciftare gli array in modo da fare un controllo in verticale
ES:
a = 1,2,3,4,5
b = 5,1,2,3,4
c = 2,3,4,5,1

Facendo così ho nella stessa posizione:
- nell'array a il valore di cui volgio sapere se è il massimo locale,
- nell'array b il valore precedente rispetto al valore presente nell'array a
- nell'array c il valore seguente rispetto al valore presente nell'array a

Di conseguenza basta che verifichi che l'elemento nell'array a sia maggiore di quelli presenti in b e c
"""

(array([2, 5, 7]),)
[ 5  7 45]


In [7]:
dict_num_maggiori_locali = {}
num_prec = array[0]

for i, val in enumerate(array):
    if i<len(array)-1:
        if val > num_prec and val > array[i+1]:
            dict_num_maggiori_locali[i] = val
        num_prec = val
    
dict_num_maggiori_locali

{2: 5, 5: 7, 7: 45}

## ESERCIZIO 4

Dato un array monodimensionale di numeri interi compresi tra 0 e 9, generato casualmente, trovare le posizioni dell'array in cui compare la sequenza di numeri [1, 2, 3].

In [51]:
array = np.random.randint(0,9,1000)

In [52]:
def search_sequence_numpy(arr,seq):
    
    # https://stackoverflow.com/questions/36522220/searching-a-sequence-in-a-numpy-array
    
    """ Find sequence in an array using NumPy only.

    Parameters
    ----------    
    arr    : input 1D array
    seq    : input 1D array

    Output
    ------    
    Output : 1D Array of indices in the input array that satisfy the 
    matching of input sequence in the input array.
    In case of no match, an empty list is returned.
    """

    # Store sizes of input array and sequence
    Na, Nseq = arr.size, seq.size

    # Range of sequence
    r_seq = np.arange(Nseq)

    # Create a 2D array of sliding indices across the entire length of input array.
    # Match up with the input sequence & get the matching starting indices.
    M = (arr[np.arange(Na-Nseq+1)[:,None] + r_seq] == seq).all(1)

    # Get the range of those indices as final output
    if M.any() >0:
        return np.where(np.convolve(M,np.ones((Nseq),dtype=int))>0)[0]
    else:
        return []         # No match found

print(array)
search_sequence_numpy(array, np.array([1,2,3]))

[1 2 1 4 1 0 8 8 0 0 3 3 8 5 7 0 2 1 6 4 7 2 4 6 7 0 1 1 6 8 3 2 0 2 1 6 5
 5 7 6 3 7 5 6 5 0 6 8 8 5 4 0 0 4 7 3 4 1 1 4 3 7 5 8 8 2 3 7 0 0 6 8 5 5
 3 0 5 2 1 7 0 8 0 3 4 3 1 8 7 0 5 3 5 8 3 4 8 6 5 4 6 3 2 2 5 0 4 6 4 1 7
 3 2 7 6 2 3 6 0 1 4 7 0 8 6 1 7 3 3 6 2 2 3 7 5 0 1 1 4 2 1 1 3 6 8 2 5 4
 3 6 8 0 1 3 3 3 1 4 6 7 4 3 4 4 6 6 3 0 4 8 7 0 7 6 7 1 1 5 4 4 0 0 6 7 4
 7 7 8 6 5 0 2 2 7 1 6 1 6 1 2 0 8 4 8 7 2 0 6 5 7 1 5 0 6 8 7 8 2 1 6 1 6
 8 2 3 6 0 4 3 1 6 2 6 4 5 2 1 7 8 7 4 0 4 0 0 4 6 7 7 6 7 5 2 6 8 6 3 5 8
 0 5 2 4 0 4 5 2 7 2 1 6 4 8 1 0 1 7 0 0 4 0 6 4 3 5 8 7 4 1 7 7 7 3 3 5 5
 7 8 8 3 2 3 7 2 0 5 1 8 7 8 0 3 1 5 7 0 6 8 6 2 7 6 0 2 7 4 0 1 8 7 4 8 0
 4 5 8 4 3 5 0 6 6 4 1 1 3 0 6 1 7 5 2 3 8 2 6 4 3 2 3 1 6 2 1 2 5 2 8 6 5
 2 3 1 2 3 0 2 1 8 4 4 1 2 3 5 3 6 7 3 0 0 3 7 1 6 8 5 6 2 2 1 8 1 6 8 7 1
 1 8 6 0 2 0 2 1 0 4 2 4 7 1 7 0 1 1 4 2 0 7 4 6 8 1 0 4 7 7 6 5 6 4 7 8 7
 7 1 8 6 7 8 8 8 4 2 0 0 4 4 7 2 1 8 7 4 1 1 0 0 2 1 6 4 0 1 7 5 4 2 1 0 0
 3 7 3 5 8 7 5 5 6 4 4 8 

array([372, 373, 374, 381, 382, 383, 670, 671, 672])

In [54]:
array = list(array)
indici = []

"""
import random

for _ in range(1000):
    array.append(random.randint(0,9))

"""
    
for i in range(1000):
    if i<1000-3:
        if array[i] == 1 and array[i+1] == 2 and array[i+2] == 3:
            for y in range(3):
                indici.append(i+y)
            
    
print(array)
print(indici)

[1, 2, 1, 4, 1, 0, 8, 8, 0, 0, 3, 3, 8, 5, 7, 0, 2, 1, 6, 4, 7, 2, 4, 6, 7, 0, 1, 1, 6, 8, 3, 2, 0, 2, 1, 6, 5, 5, 7, 6, 3, 7, 5, 6, 5, 0, 6, 8, 8, 5, 4, 0, 0, 4, 7, 3, 4, 1, 1, 4, 3, 7, 5, 8, 8, 2, 3, 7, 0, 0, 6, 8, 5, 5, 3, 0, 5, 2, 1, 7, 0, 8, 0, 3, 4, 3, 1, 8, 7, 0, 5, 3, 5, 8, 3, 4, 8, 6, 5, 4, 6, 3, 2, 2, 5, 0, 4, 6, 4, 1, 7, 3, 2, 7, 6, 2, 3, 6, 0, 1, 4, 7, 0, 8, 6, 1, 7, 3, 3, 6, 2, 2, 3, 7, 5, 0, 1, 1, 4, 2, 1, 1, 3, 6, 8, 2, 5, 4, 3, 6, 8, 0, 1, 3, 3, 3, 1, 4, 6, 7, 4, 3, 4, 4, 6, 6, 3, 0, 4, 8, 7, 0, 7, 6, 7, 1, 1, 5, 4, 4, 0, 0, 6, 7, 4, 7, 7, 8, 6, 5, 0, 2, 2, 7, 1, 6, 1, 6, 1, 2, 0, 8, 4, 8, 7, 2, 0, 6, 5, 7, 1, 5, 0, 6, 8, 7, 8, 2, 1, 6, 1, 6, 8, 2, 3, 6, 0, 4, 3, 1, 6, 2, 6, 4, 5, 2, 1, 7, 8, 7, 4, 0, 4, 0, 0, 4, 6, 7, 7, 6, 7, 5, 2, 6, 8, 6, 3, 5, 8, 0, 5, 2, 4, 0, 4, 5, 2, 7, 2, 1, 6, 4, 8, 1, 0, 1, 7, 0, 0, 4, 0, 6, 4, 3, 5, 8, 7, 4, 1, 7, 7, 7, 3, 3, 5, 5, 7, 8, 8, 3, 2, 3, 7, 2, 0, 5, 1, 8, 7, 8, 0, 3, 1, 5, 7, 0, 6, 8, 6, 2, 7, 6, 0, 2, 7, 4, 0, 1, 8, 7, 4, 8, 0, 

## ESERCIZIO 5

Sul territorio comunale sono installate tre centraline per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta le centraline vanno in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni. Inoltre, per motivi sconosciuti, talvolta le centraline riportano il valore -1. Statisticamente si è visto che il primo errore ha una frequenza dello 0.2% mentre il secondo del 0.1%

- Creare una matrice avente 3 colonne e le righe contenente i dati di tutte le centraline registrati nelle 24 ore (si registra il dato ogni minuto)
- Eliminare tutte le righe della matrice in cui vi sia almeno una misura errata o una misura di origine sconosciuta

In [71]:
num_minuti = 24*60
valore_0_2_non_percentuale = 0.2/100
valore_0_1_non_percentuale = 0.1/100

In [109]:
def num_random(a):
    val = np.random.random()
    if val < valore_0_1_non_percentuale:
        return 9999
    elif val < valore_0_2_non_percentuale:
        return -1
    else:
        return np.random.randint(0,40)


num_random_v = np.vectorize(num_random)

matrice = np.ones((num_minuti, 3))

matrice = num_random_v(matrice)

# vado a verificare per ogni colonna la presenza di 9999 e -1 
for i in range(3):
    b_9 += matrice[:,i] == 9999
    b_1 +=  matrice[:,i] == -1

print(list(matrice))

# sommo gli array di bool in modo da trovare sia dove sono presenti i 9999 che i -1
print(list(matrice[np.invert(b_9+b_1)]))  

[array([37, 16, 35]), array([29, 33,  8]), array([11,  4, 13]), array([10,  7, 32]), array([18, 35, 36]), array([30, 37, 23]), array([ 7, 24, 39]), array([11, 23,  0]), array([ 1, 18, 34]), array([39, 17, 39]), array([14, 17,  4]), array([ 6, 39, 28]), array([37, 10, 32]), array([19, 19, 35]), array([17, 14, 23]), array([29, 14, 30]), array([ 6, 39,  5]), array([ 1, 39,  4]), array([24, 31,  4]), array([ 7, 22, 15]), array([18, 23,  9]), array([36, 19, 14]), array([30, 22,  7]), array([ 2,  4, 34]), array([ 2, 12, 16]), array([ 1, 24, 37]), array([20, 38, 10]), array([31, 17, 31]), array([17, 11, 20]), array([15, 23, 29]), array([10, 26, 17]), array([26,  1,  4]), array([30, 24, 32]), array([15, 18,  4]), array([12, 30, 35]), array([ 1, 15, 38]), array([ 4,  9, 10]), array([25,  9, 12]), array([30, 18, 16]), array([ 7, 26,  6]), array([ 9, 18,  7]), array([ 1,  0, 36]), array([25, 35, 27]), array([ 4, 13,  2]), array([0, 9, 6]), array([35, 33,  8]), array([28, 24, 10]), array([23,  2, 

In [110]:
import random

# generatore di numeri random
def num_random():
    val = random.random()
    if val < valore_0_1_non_percentuale:
        return 9999.9
    elif val < valore_0_2_non_percentuale:
        return -1
    else:
        return random.randint(0,40)
    

# creazione matrice
matrice = []
for _ in range(num_minuti):
    
    riga = []
    
    for _ in range(3):
        riga.append(num_random())
        
    matrice.append(riga)
    
print(matrice)

# trovare gli array da eliminare
array_indici_da_eliminare = []
for i, val in enumerate(matrice):
    if -1 in val or 9999.9 in val:
        matrice.pop(i)

print("\n\n")
print(matrice)
            
            
    

[[37, 10, 4], [7, 0, 30], [30, 28, 21], [30, 15, 24], [22, 23, 13], [11, 0, 40], [32, 35, 32], [36, 26, 39], [31, 19, 32], [9, 38, 21], [12, 36, 33], [26, 24, 16], [0, 23, 38], [16, 11, 16], [6, 15, 18], [26, 9, 15], [3, 27, 32], [36, 26, 22], [5, 32, 2], [12, 1, 28], [16, 32, 39], [24, 1, 5], [39, 30, 6], [34, 10, 8], [27, 9, 25], [30, 28, 33], [1, 36, 40], [2, 21, 16], [28, 30, 19], [3, 26, 6], [38, 21, 11], [26, 22, 30], [33, 16, 35], [0, 30, 31], [22, 19, 0], [36, 20, 34], [31, 36, 1], [25, 33, 39], [5, 35, 21], [26, 10, 16], [32, 36, 24], [7, 40, 18], [39, 26, 12], [19, 13, 15], [36, 25, 19], [17, 28, 4], [9, 23, 27], [3, 24, 33], [6, 22, 13], [22, 12, 14], [16, 28, 19], [20, 6, 26], [20, 8, 9], [5, 36, 1], [38, 36, 21], [39, 31, 6], [26, 28, 4], [1, 9, 16], [36, 40, 13], [8, 5, 32], [1, 33, 19], [39, 7, 1], [19, 20, 33], [11, 0, 20], [7, 1, 35], [13, 36, 28], [8, 21, 11], [2, 24, 24], [35, 35, 27], [23, 38, 37], [9, 14, 1], [23, 2, 29], [19, 38, 30], [10, 22, 20], [11, 2, 6], [35